#include <bits/stdc++.h>
using namespace std;
int main(){
//	int a;
//	cin>>a;
////	first-condition
//	check the value is negative and possitive 
//	if(a>0){
//		cout<<"value is possitive";
//	}
//	else{
//		cout<<"value is negative";
//	}
//
//
////second-condition
//if(a<=12){
//	cout<<"value is small";
//}
//if(a>=13 && a<=20){
//	cout<<"value is neagative";
//}
//else{
//cout<<"check value";
//}
//
////third-condition
//if(a<=12){
//	cout<<"value is small";
//}
//else if(a>=13){
//	cout<<"value is neagative";
//}
//}


//if if me 2 condition follow hoti ha to 2 print ho guy ge
//Q.1
//int a=9;
//if(a==9){
//	cout<<"NINE";
//}
//if(a>0){
//	cout<<"positive";
//}
//else{
//	cout<<"negative";
//}


//Q.2
//int a=2;
//int b=a+1;
//if((a=3)==b){
//	cout<<a;
//}
//else{
//	cout<<a+1;
//}

//Q.3
//int a=2;
//int b=a+1;
//if((a=4)==b){
//	cout<<"a";
//}
//else{
//	cout<<a+1;
//}

//Q.4
//if and else if me 2 condition follow ho ti ha to bhi but 1 condition print hogi
//int a=24;
//if(a>20){
//	cout<<"love";
//}
//else if(a==24){
//	cout<<"lovely";
//}
//else{
//	cout<<"babber";
//}
//cout<<a;

//Q.5
//char ch;
//cin>>ch;
//if(ch>='a'&& ch<='z'){
//	cout<<"This is lower case";
//}
//if(ch>='A'&& ch<='Z'){
//	cout<<"This is upper case";
//} 
//if(ch>='0'&& ch<='9'){
//	cout<<"This is numeric";
//}
//else{
//	cout<<"check value";
//}


//Q.6
//print the value 1 to n
//int n;
//cin>>n;
//int  i=1;
//while(i<=n){
//	cout<<i<<"\n";
//	i++;

//Q.7
//print the sum of 1 to n e.g=>1+2+3+4+......+n
//int n;
//cin>>n;
//int i=1,sum=0;
//while(i<=n){
//	sum=sum+i;
//	i=i+1;
////	not use i++ here;
//}       
//cout<<sum;

//Q.8
//#include<bits/stdc++.h>
//using namespace std;
//int main(){
//int n;
//cin>>n;
//int i=2,sum=0;
//while(i<=n){
//	sum=sum+i;
//	i=i+2;
////	even ke leya 2 ka increment ho raha ha
//}
//cout<<sum;
//return 0;

   
//Q.9
//int n;
//cin>>n;
//
//int i=2;
//while(i<n){
////	prime me remainder 0 nahi ho chaiya
//	if(n%i==0){
//		cout<<"not a prime"<<i;
//	}
//	else{
//		cout<<"prime for"<<i;
//	}
//	i=i+1;
// }
//} 









